import bcrypt from 'bcryptjs';
import type {
  User,
  Service,
  Booking,
  EscrowTransaction,
  Notification,
  JobRequest,
  Conversation,
  Message,
} from '@/src/lib/types';

const h = (plain: string) => bcrypt.hashSync(plain, 10);


// Users

export const MOCK_USERS: User[] = [
  {
    id: 'user_c1',
    email: 'mubarak@servihub.dev',
    passwordHash: h('client123'),
    name: 'Mubarak Eze',
    role: 'CLIENT',
    bio: 'Property developer in Lekki. Frequently hire skilled tradespeople for renovation and new builds.',
    location: 'Lagos',
    preferredCurrency: 'NGN',
    isVerified: true,
    createdAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'user_c2',
    email: 'ibiso@servihub.dev',
    passwordHash: h('client123'),
    name: 'Ibiso Bankole',
    role: 'CLIENT',
    bio: 'Business owner running a construction supply company. Regularly contract craftspeople for client projects.',
    location: 'Lagos',
    preferredCurrency: 'NGN',
    isVerified: true,
    createdAt: '2024-10-02T08:30:00Z',
  },
  {
    id: 'user_c3',
    email: 'daniel@servihub.dev',
    passwordHash: h('client123'),
    name: 'Daniel Usman',
    role: 'CLIENT',
    bio: 'Civil servant in Abuja. Renovating family home and looking for reliable artisans.',
    location: 'Abuja',
    preferredCurrency: 'NGN',
    isVerified: true,
    createdAt: '2024-11-20T14:15:00Z',
  },
  {
    id: 'user_c4',
    email: 'chukwuma@servihub.dev',
    passwordHash: h('client123'),
    name: 'Chukwuma Obi',
    role: 'CLIENT',
    bio: 'Hotel owner in Enugu seeking maintenance and interior teams for seasonal refurbishments.',
    location: 'Enugu',
    preferredCurrency: 'NGN',
    isVerified: false,
    createdAt: '2024-12-05T09:00:00Z',
  },
  {
    id: 'user_c5',
    email: 'yemi@servihub.dev',
    passwordHash: h('client123'),
    name: 'Yemi Adesanya',
    role: 'CLIENT',
    bio: 'Landlord managing multiple properties across Ibadan. Need fast, trustworthy tradespeople.',
    location: 'Ibadan',
    preferredCurrency: 'NGN',
    isVerified: true,
    createdAt: '2025-01-08T11:00:00Z',
  },
  {
    id: 'user_c6',
    email: 'hauwa@servihub.dev',
    passwordHash: h('client123'),
    name: 'Hauwa Musa',
    role: 'CLIENT',
    bio: 'Fashion boutique owner in Kano building a flagship store. Need electrical, interior and painting work.',
    location: 'Kano',
    preferredCurrency: 'NGN',
    isVerified: false,
    createdAt: '2025-01-15T13:00:00Z',
  },

  // ── Providers
  {
    id: 'user_p1',
    email: 'victor@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Victor Adeyemi',
    role: 'PROVIDER',
    bio: 'Master electrician with 12 years of experience. Certified by NERC. Specialises in residential and commercial wiring, solar installations, and industrial panel upgrades.',
    location: 'Lagos',
    preferredCurrency: 'NGN',
    rating: 4.92,
    reviewCount: 94,
    hourlyRate: 9000,
    skills: ['Wiring', 'Solar Installation', 'Panel Upgrade', 'Generator', 'CCTV'],
    isVerified: true,
    createdAt: '2024-08-01T09:00:00Z',
  },
  {
    id: 'user_p2',
    email: 'emmanuel@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Emmanuel Okonkwo',
    role: 'PROVIDER',
    bio: 'Expert carpenter and furniture maker based in Abuja. Crafts custom wardrobes, kitchens, and office furniture using both hardwood and engineered boards.',
    location: 'Abuja',
    preferredCurrency: 'NGN',
    rating: 4.85,
    reviewCount: 67,
    hourlyRate: 8000,
    skills: ['Furniture Making', 'Kitchen Cabinets', 'Door Fitting', 'Wardrobes', 'Decking'],
    isVerified: true,
    createdAt: '2024-07-15T11:00:00Z',
  },
  {
    id: 'user_p3',
    email: 'taiwo@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Taiwo Ogundimu',
    role: 'PROVIDER',
    bio: 'Professional painter and decorator. 9 years experience in textured wall finishes, epoxy floors, and standard emulsion painting for homes and commercial spaces.',
    location: 'Lagos',
    preferredCurrency: 'NGN',
    rating: 4.78,
    reviewCount: 53,
    hourlyRate: 6000,
    skills: ['Wall Painting', 'Epoxy Flooring', 'Textured Finishes', 'Waterproofing', 'Exterior Painting'],
    isVerified: true,
    createdAt: '2024-09-01T13:30:00Z',
  },
  {
    id: 'user_p4',
    email: 'musa@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Musa Ibrahim',
    role: 'PROVIDER',
    bio: 'Licensed plumber with expertise in borehole installations, pipe laying, drainage systems, and overhead tank setups across residential and commercial sites.',
    location: 'Kano',
    preferredCurrency: 'NGN',
    rating: 4.72,
    reviewCount: 41,
    hourlyRate: 7500,
    skills: ['Pipe Laying', 'Borehole', 'Drainage', 'Overhead Tanks', 'Bathroom Fitting'],
    isVerified: true,
    createdAt: '2024-10-10T10:00:00Z',
  },
  {
    id: 'user_p5',
    email: 'emeka@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Emeka Nwosu',
    role: 'PROVIDER',
    bio: 'Seasoned bricklayer and mason based in Enugu. Builds block walls, lays foundation, and constructs fences and retaining walls for residential and commercial clients.',
    location: 'Enugu',
    preferredCurrency: 'NGN',
    rating: 4.65,
    reviewCount: 38,
    hourlyRate: 10000,
    skills: ['Block Laying', 'Foundation', 'Fence Construction', 'Rendering', 'Tiling'],
    isVerified: true,
    createdAt: '2024-11-05T08:00:00Z',
  },
  {
    id: 'user_p6',
    email: 'aisha@servihub.dev',
    passwordHash: h('provider123'),
    name: 'Aisha Sule',
    role: 'PROVIDER',
    bio: 'Interior designer and space consultant with a portfolio spanning Lagos and Abuja. Transforms living rooms, kitchens, and offices into functional, beautiful spaces.',
    location: 'Abuja',
    preferredCurrency: 'NGN',
    rating: 4.88,
    reviewCount: 49,
    hourlyRate: 15000,
    skills: ['Space Planning', 'Furniture Sourcing', 'Colour Consultation', 'Kitchen Design', 'Lighting'],
    isVerified: true,
    createdAt: '2024-08-20T14:00:00Z',
  },
];


// Services — all prices in NGN


export const MOCK_SERVICES: Service[] = [
  {
    id: 'svc_01',
    providerId: 'user_p1',
    title: 'Full Home Electrical Rewiring',
    description: 'Complete rewiring of a 3–4 bedroom house including new consumer unit, all sockets, switches, lighting points, and earthing. NERC-compliant installation with test certificate.',
    category: 'Electrical',
    price: 180000,
    priceType: 'FIXED',
    rating: 4.95,
    reviewCount: 38,
    deliveryTime: 7,
    tags: ['rewiring', 'consumer unit', 'residential', 'NERC certified'],
    isActive: true,
    createdAt: '2024-08-05T09:00:00Z',
  },
  {
    id: 'svc_02',
    providerId: 'user_p1',
    title: 'Electrical Repairs & Fault Diagnosis',
    description: 'Emergency callout for any electrical fault. Tripped breakers, power surges, socket failures, flickering lights — diagnosed and fixed same day.',
    category: 'Electrical',
    price: 9000,
    priceType: 'HOURLY',
    rating: 4.9,
    reviewCount: 47,
    deliveryTime: 1,
    tags: ['repair', 'emergency', 'fault finding', 'same day'],
    isActive: true,
    createdAt: '2024-08-05T09:30:00Z',
  },
  {
    id: 'svc_03',
    providerId: 'user_p2',
    title: 'Custom Kitchen Cabinet Installation',
    description: 'Fully bespoke kitchen cabinetry — wall units, base units, island, and pantry — made to measure from hardwood or board. Includes worktop fitting.',
    category: 'Carpentry',
    price: 320000,
    priceType: 'FIXED',
    rating: 4.87,
    reviewCount: 29,
    deliveryTime: 14,
    tags: ['kitchen', 'cabinets', 'custom', 'hardwood', 'installation'],
    isActive: true,
    createdAt: '2024-07-20T11:00:00Z',
  },
  {
    id: 'svc_04',
    providerId: 'user_p2',
    title: 'Custom Wardrobes & Fitted Furniture',
    description: 'Built-in sliding wardrobes, TV units, and fitted shelving designed around your space. Delivered and installed within 2 weeks.',
    category: 'Carpentry',
    price: 250000,
    priceType: 'FIXED',
    rating: 4.82,
    reviewCount: 24,
    deliveryTime: 14,
    tags: ['wardrobe', 'sliding doors', 'fitted furniture', 'bedroom'],
    isActive: true,
    createdAt: '2024-07-22T12:00:00Z',
  },
  {
    id: 'svc_05',
    providerId: 'user_p3',
    title: 'Interior House Painting (Full Property)',
    description: 'Full interior repaint of a 3-bedroom flat using premium emulsion. Includes wall prep, filling, sanding, primer coat, and two finish coats. Clean, sharp lines guaranteed.',
    category: 'Painting',
    price: 120000,
    priceType: 'FIXED',
    rating: 4.8,
    reviewCount: 31,
    deliveryTime: 5,
    tags: ['interior', 'emulsion', 'residential', 'premium'],
    isActive: true,
    createdAt: '2024-09-05T14:00:00Z',
  },
  {
    id: 'svc_06',
    providerId: 'user_p3',
    title: 'Epoxy Floor Coating',
    description: 'High-gloss epoxy floor application for garages, warehouses, and commercial kitchens. Dust-proof, chemical-resistant, and available in 12 colours.',
    category: 'Painting',
    price: 85000,
    priceType: 'FIXED',
    rating: 4.75,
    reviewCount: 18,
    deliveryTime: 3,
    tags: ['epoxy', 'floor', 'garage', 'commercial', 'waterproof'],
    isActive: true,
    createdAt: '2024-09-08T15:00:00Z',
  },
  {
    id: 'svc_07',
    providerId: 'user_p4',
    title: 'Borehole Drilling & Pump Installation',
    description: 'Complete borehole solution — drilling, casing, submersible pump, overhead tank connection, and pressure testing. 12-month pump warranty included.',
    category: 'Plumbing',
    price: 380000,
    priceType: 'FIXED',
    rating: 4.78,
    reviewCount: 22,
    deliveryTime: 5,
    tags: ['borehole', 'pump', 'water supply', 'drilling'],
    isActive: true,
    createdAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'svc_08',
    providerId: 'user_p4',
    title: 'Bathroom & Toilet Fitting',
    description: 'Full bathroom installation — WC, shower tray, bath, basin, taps, and tile board. Supply and fit or fit-only options available.',
    category: 'Plumbing',
    price: 7500,
    priceType: 'HOURLY',
    rating: 4.65,
    reviewCount: 15,
    deliveryTime: 3,
    tags: ['bathroom', 'toilet', 'shower', 'basin', 'fitting'],
    isActive: true,
    createdAt: '2024-10-20T11:00:00Z',
  },
  {
    id: 'svc_09',
    providerId: 'user_p5',
    title: 'Perimeter Fence Construction',
    description: 'Block and render fence construction for residential and commercial properties. Includes gate pillars, coping, and plastering. Priced per linear metre.',
    category: 'Masonry',
    price: 95000,
    priceType: 'FIXED',
    rating: 4.7,
    reviewCount: 19,
    deliveryTime: 10,
    tags: ['fence', 'block', 'perimeter', 'security', 'plastering'],
    isActive: true,
    createdAt: '2024-11-10T09:00:00Z',
  },
  {
    id: 'svc_10',
    providerId: 'user_p5',
    title: 'Foundation & Substructure Works',
    description: 'Strip foundation, raft foundation, and block work up to DPC. Experienced team for residential buildings from 1 to 4 floors.',
    category: 'Masonry',
    price: 10000,
    priceType: 'HOURLY',
    rating: 4.6,
    reviewCount: 12,
    deliveryTime: 21,
    tags: ['foundation', 'DPC', 'block laying', 'substructure'],
    isActive: true,
    createdAt: '2024-11-12T10:00:00Z',
  },
  {
    id: 'svc_11',
    providerId: 'user_p6',
    title: 'Full Living Room Interior Design',
    description: 'End-to-end living room transformation — space planning, furniture selection, colour palette, soft furnishings, lighting plan, and supplier coordination.',
    category: 'Interior Design',
    price: 280000,
    priceType: 'FIXED',
    rating: 4.9,
    reviewCount: 26,
    deliveryTime: 21,
    tags: ['living room', 'interior', 'furniture', 'lighting', 'design'],
    isActive: true,
    createdAt: '2024-08-25T15:00:00Z',
  },
  {
    id: 'svc_12',
    providerId: 'user_p6',
    title: 'Design Consultation (Per Session)',
    description: 'A focused 2-hour on-site consultation covering layout, colours, materials, and priority upgrades. Includes a written brief and mood board.',
    category: 'Interior Design',
    price: 15000,
    priceType: 'HOURLY',
    rating: 4.85,
    reviewCount: 34,
    deliveryTime: 1,
    tags: ['consultation', 'mood board', 'colours', 'quick win'],
    isActive: true,
    createdAt: '2024-08-28T16:00:00Z',
  },
];


// Bookings — amounts in NGN


export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bkg_01',
    serviceId: 'svc_01',
    clientId: 'user_c1',
    providerId: 'user_p1',
    status: 'RELEASED',
    totalAmount: 180000,
    platformFee: 18000,
    escrowAmount: 180000,
    upfrontPaid: true,
    completionPaid: true,
    description: 'Full rewiring of my 4-bedroom duplex in Lekki Phase 1. Existing wiring is 20+ years old.',
    startDate: '2024-10-01T09:00:00Z',
    completionDate: '2024-10-08T17:00:00Z',
    createdAt: '2024-09-28T10:00:00Z',
  },
  {
    id: 'bkg_02',
    serviceId: 'svc_05',
    clientId: 'user_c1',
    providerId: 'user_p3',
    status: 'IN_PROGRESS',
    totalAmount: 120000,
    platformFee: 12000,
    escrowAmount: 120000,
    upfrontPaid: true,
    completionPaid: false,
    description: 'Paint entire interior of my 3-bedroom flat in Victoria Island. Prefer off-white/cream tones.',
    startDate: '2025-01-10T09:00:00Z',
    createdAt: '2025-01-08T14:00:00Z',
  },
  {
    id: 'bkg_03',
    serviceId: 'svc_07',
    clientId: 'user_c1',
    providerId: 'user_p4',
    status: 'PENDING',
    totalAmount: 380000,
    platformFee: 38000,
    escrowAmount: 0,
    upfrontPaid: false,
    completionPaid: false,
    description: 'New borehole for my compound in Surulere. Need full installation including pump and tank connection.',
    startDate: '2025-02-15T09:00:00Z',
    createdAt: '2025-01-22T11:00:00Z',
  },
  {
    id: 'bkg_04',
    serviceId: 'svc_03',
    clientId: 'user_c2',
    providerId: 'user_p2',
    status: 'ESCROW_PAID',
    totalAmount: 320000,
    platformFee: 32000,
    escrowAmount: 320000,
    upfrontPaid: false,
    completionPaid: false,
    description: 'Kitchen cabinets for a client showroom in Ikeja. Full L-shape layout, 22 units total.',
    startDate: '2025-01-20T09:00:00Z',
    createdAt: '2025-01-18T09:00:00Z',
  },
  {
    id: 'bkg_05',
    serviceId: 'svc_11',
    clientId: 'user_c3',
    providerId: 'user_p6',
    status: 'RELEASED',
    totalAmount: 280000,
    platformFee: 28000,
    escrowAmount: 280000,
    upfrontPaid: true,
    completionPaid: true,
    description: 'Transform our sitting room in Maitama. Open plan, needs a fresh contemporary feel.',
    startDate: '2024-11-10T09:00:00Z',
    completionDate: '2024-12-01T17:00:00Z',
    createdAt: '2024-11-05T10:00:00Z',
  },
  {
    id: 'bkg_06',
    serviceId: 'svc_09',
    clientId: 'user_c4',
    providerId: 'user_p5',
    status: 'IN_PROGRESS',
    totalAmount: 95000,
    platformFee: 9500,
    escrowAmount: 95000,
    upfrontPaid: true,
    completionPaid: false,
    description: 'Perimeter fence for hotel annex property in GRA Enugu. Approx 80 linear metres.',
    startDate: '2025-01-25T09:00:00Z',
    createdAt: '2025-01-20T14:00:00Z',
  },
  {
    id: 'bkg_07',
    serviceId: 'svc_02',
    clientId: 'user_c5',
    providerId: 'user_p1',
    status: 'COMPLETED',
    totalAmount: 54000,
    platformFee: 5400,
    escrowAmount: 54000,
    upfrontPaid: true,
    completionPaid: false,
    description: 'Power tripping in two apartments at Bodija. Likely overloaded circuits — needs inspection and upgrade.',
    startDate: '2025-01-15T09:00:00Z',
    completionDate: '2025-01-15T16:00:00Z',
    createdAt: '2025-01-13T11:00:00Z',
  },
  {
    id: 'bkg_08',
    serviceId: 'svc_06',
    clientId: 'user_c6',
    providerId: 'user_p3',
    status: 'DECLINED',
    totalAmount: 85000,
    platformFee: 8500,
    escrowAmount: 0,
    upfrontPaid: false,
    completionPaid: false,
    description: 'Epoxy coating for boutique showroom floor in Kano. 120sqm space.',
    startDate: '2025-02-01T09:00:00Z',
    createdAt: '2025-01-20T15:00:00Z',
  },
];


// Escrow transactions — amounts in NGN


export const MOCK_ESCROW_TRANSACTIONS: EscrowTransaction[] = [
  { id: 'esc_01', bookingId: 'bkg_01', amount: 180000, type: 'DEPOSIT',             status: 'COMPLETED', createdAt: '2024-09-28T10:10:00Z' },
  { id: 'esc_02', bookingId: 'bkg_01', amount: 90000,  type: 'UPFRONT_RELEASE',     status: 'COMPLETED', createdAt: '2024-10-01T09:30:00Z' },
  { id: 'esc_03', bookingId: 'bkg_01', amount: 72000,  type: 'COMPLETION_RELEASE',  status: 'COMPLETED', createdAt: '2024-10-08T18:00:00Z' },
  { id: 'esc_04', bookingId: 'bkg_01', amount: 18000,  type: 'PLATFORM_FEE',        status: 'COMPLETED', createdAt: '2024-10-08T18:01:00Z' },
  { id: 'esc_05', bookingId: 'bkg_02', amount: 120000, type: 'DEPOSIT',             status: 'COMPLETED', createdAt: '2025-01-08T14:10:00Z' },
  { id: 'esc_06', bookingId: 'bkg_02', amount: 60000,  type: 'UPFRONT_RELEASE',     status: 'COMPLETED', createdAt: '2025-01-10T09:30:00Z' },
  { id: 'esc_07', bookingId: 'bkg_05', amount: 280000, type: 'DEPOSIT',             status: 'COMPLETED', createdAt: '2024-11-05T10:05:00Z' },
  { id: 'esc_08', bookingId: 'bkg_05', amount: 252000, type: 'COMPLETION_RELEASE',  status: 'COMPLETED', createdAt: '2024-12-01T17:30:00Z' },
];


// Conversations


export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_01',
    participants: ['user_c1', 'user_p3'],
    bookingId: 'bkg_02',
    lastMessage: "I'll start with the master bedroom tomorrow morning at 8am.",
    lastMessageAt: '2025-01-12T17:45:00Z',
    unreadCount: { user_c1: 1, user_p3: 0 },
    createdAt: '2025-01-08T15:00:00Z',
  },
  {
    id: 'conv_02',
    participants: ['user_c2', 'user_p2'],
    bookingId: 'bkg_04',
    lastMessage: 'Please confirm the hinge type — soft-close or standard?',
    lastMessageAt: '2025-01-19T11:20:00Z',
    unreadCount: { user_c2: 0, user_p2: 1 },
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'conv_03',
    participants: ['user_c1', 'user_p4'],
    bookingId: 'bkg_03',
    lastMessage: 'Good afternoon, Musa. When can you come for the site assessment?',
    lastMessageAt: '2025-01-23T13:10:00Z',
    unreadCount: { user_c1: 0, user_p4: 1 },
    createdAt: '2025-01-22T12:00:00Z',
  },
  {
    id: 'conv_04',
    participants: ['user_c4', 'user_p5'],
    bookingId: 'bkg_06',
    lastMessage: 'The gate pillars are done. Starting on the main fence run tomorrow.',
    lastMessageAt: '2025-01-27T16:30:00Z',
    unreadCount: { user_c4: 2, user_p5: 0 },
    createdAt: '2025-01-20T15:00:00Z',
  },
];

// Messages


export const MOCK_MESSAGES: Message[] = [
  // conv_01 — Mubarak ↔ Taiwo (painting job)
  {
    id: 'msg_01',
    conversationId: 'conv_01',
    senderId: 'user_c1',
    receiverId: 'user_p3',
    content: 'Hello Taiwo, I just confirmed the booking. When can we expect you to start?',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-08T15:05:00Z',
  },
  {
    id: 'msg_02',
    conversationId: 'conv_01',
    senderId: 'user_p3',
    receiverId: 'user_c1',
    content: 'Good day Ma. I can be on site Monday morning. We will start with the prep work — filling cracks and sanding.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-08T16:00:00Z',
  },
  {
    id: 'msg_03',
    conversationId: 'conv_01',
    senderId: 'user_c1',
    receiverId: 'user_p3',
    content: 'Perfect. Please make sure the team brings dust sheets. My furniture is still in the rooms.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-09T08:30:00Z',
  },
  {
    id: 'msg_04',
    conversationId: 'conv_01',
    senderId: 'user_p3',
    receiverId: 'user_c1',
    content: "Noted Ma. We always bring our own protection materials. I'll start with the master bedroom tomorrow morning at 8am.",
    type: 'TEXT',
    isRead: false,
    createdAt: '2025-01-12T17:45:00Z',
  },

  // conv_02 — Ibiso ↔ Emmanuel (kitchen cabinets)
  {
    id: 'msg_05',
    conversationId: 'conv_02',
    senderId: 'user_c2',
    receiverId: 'user_p2',
    content: 'Emmanuel, I have approved the quote. The showroom dimensions are in the PDF I sent.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-18T10:05:00Z',
  },
  {
    id: 'msg_06',
    conversationId: 'conv_02',
    senderId: 'user_p2',
    receiverId: 'user_c2',
    content: 'Thank you sir. I received the PDF. I will fabricate using 18mm moisture-resistant board as discussed.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-18T12:00:00Z',
  },
  {
    id: 'msg_07',
    conversationId: 'conv_02',
    senderId: 'user_p2',
    receiverId: 'user_c2',
    content: 'Please confirm the hinge type — soft-close or standard?',
    type: 'TEXT',
    isRead: false,
    createdAt: '2025-01-19T11:20:00Z',
  },

  // conv_03 — Mubarak ↔ Musa (borehole)
  {
    id: 'msg_08',
    conversationId: 'conv_03',
    senderId: 'user_c1',
    receiverId: 'user_p4',
    content: 'Good afternoon, Musa. When can you come for the site assessment?',
    type: 'TEXT',
    isRead: false,
    createdAt: '2025-01-23T13:10:00Z',
  },

  // conv_04 — Chukwuma ↔ Emeka (fence)
  {
    id: 'msg_09',
    conversationId: 'conv_04',
    senderId: 'user_p5',
    receiverId: 'user_c4',
    content: 'Good morning sir. We have mobilised to site and started setting out the fence line.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-25T08:00:00Z',
  },
  {
    id: 'msg_10',
    conversationId: 'conv_04',
    senderId: 'user_c4',
    receiverId: 'user_p5',
    content: 'Good. Please ensure the gate openings are as per the drawings I sent.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 'msg_11',
    conversationId: 'conv_04',
    senderId: 'user_p5',
    receiverId: 'user_c4',
    content: 'The gate pillars are done. Starting on the main fence run tomorrow.',
    type: 'TEXT',
    isRead: false,
    createdAt: '2025-01-27T16:30:00Z',
  },
];

// Job Requests (from clients — providers can browse these)


export const MOCK_JOB_REQUESTS: JobRequest[] = [
  {
    id: 'job_01',
    clientId: 'user_c1',
    title: 'Solar Panel Installation — 5kVA System',
    description: 'I need a 5kVA solar hybrid system installed at my duplex in Lekki Phase 1. Roof space is available. Looking for a certified engineer who can also handle the inverter and battery bank.',
    category: 'Electrical',
    budgetMin: 800000,
    budgetMax: 1200000,
    location: 'Lagos',
    urgency: 'WITHIN_WEEK',
    status: 'OPEN',
    createdAt: '2025-01-24T09:00:00Z',
  },
  {
    id: 'job_02',
    clientId: 'user_c2',
    title: 'Office Electrical Installation (New Build)',
    description: 'Fit-out of a 200sqm open-plan office in Ikeja. Needs full electrical first fix and second fix — data points, sockets, lighting tracks, and a dedicated server room with UPS.',
    category: 'Electrical',
    budgetMin: 350000,
    budgetMax: 600000,
    location: 'Lagos',
    urgency: 'WITHIN_WEEK',
    status: 'OPEN',
    createdAt: '2025-01-23T11:00:00Z',
  },
  {
    id: 'job_03',
    clientId: 'user_c3',
    title: 'Bathroom & Kitchen Tiling — 3-Bedroom Flat',
    description: 'Looking for an experienced tiler for a full 3-bed apartment in Wuse II. Supply and fix. Prefer large-format tiles (600×1200). Must have portfolio to share.',
    category: 'Tiling',
    budgetMin: 180000,
    budgetMax: 280000,
    location: 'Abuja',
    urgency: 'FLEXIBLE',
    status: 'OPEN',
    createdAt: '2025-01-22T14:00:00Z',
  },
  {
    id: 'job_04',
    clientId: 'user_c4',
    title: 'Hotel Rooms Repainting — 12 Rooms',
    description: 'Annual repaint of 12 standard hotel rooms plus 2 suites in GRA Enugu. Walls and ceilings only (woodwork already done). Need a team that can work over 10 days.',
    category: 'Painting',
    budgetMin: 200000,
    budgetMax: 350000,
    location: 'Enugu',
    urgency: 'WITHIN_WEEK',
    status: 'OPEN',
    createdAt: '2025-01-21T10:00:00Z',
  },
  {
    id: 'job_05',
    clientId: 'user_c5',
    title: 'Plumbing Repairs — Multiple Units',
    description: 'Multiple plumbing issues across 4 rental units in Bodija — leaking pipes, blocked drains, and two faulty WCs. Experienced plumber needed for a full day.',
    category: 'Plumbing',
    budgetMin: 30000,
    budgetMax: 60000,
    location: 'Ibadan',
    urgency: 'URGENT',
    status: 'OPEN',
    createdAt: '2025-01-25T08:00:00Z',
  },
  {
    id: 'job_06',
    clientId: 'user_c6',
    title: 'Shop Fit-Out Interior Design',
    description: 'Need an interior designer to plan and execute the fit-out of a 90sqm fashion boutique in Kano. Must source locally where possible. Looking for a modern, clean aesthetic.',
    category: 'Interior Design',
    budgetMin: 150000,
    budgetMax: 300000,
    location: 'Kano',
    urgency: 'FLEXIBLE',
    status: 'OPEN',
    createdAt: '2025-01-26T15:00:00Z',
  },
  {
    id: 'job_07',
    clientId: 'user_c1',
    title: 'Garden Landscaping & Paving',
    description: 'Rear garden of a corner duplex needs landscaping — block-paved driveway extension, flower beds, and a small retaining wall. Area is approximately 120sqm.',
    category: 'Landscaping',
    budgetMin: 120000,
    budgetMax: 200000,
    location: 'Lagos',
    urgency: 'FLEXIBLE',
    status: 'OPEN',
    createdAt: '2025-01-20T12:00:00Z',
  },
  {
    id: 'job_08',
    clientId: 'user_c3',
    title: 'Custom Wardrobe for Master Bedroom',
    description: 'Looking for a carpenter to build a floor-to-ceiling fitted wardrobe in the master bedroom of our Abuja apartment. Sliding doors, internal drawers, and mirror panel preferred.',
    category: 'Carpentry',
    budgetMin: 180000,
    budgetMax: 320000,
    location: 'Abuja',
    urgency: 'FLEXIBLE',
    status: 'OPEN',
    createdAt: '2025-01-27T10:00:00Z',
  },
];

// Notifications


export const MOCK_NOTIFICATIONS: Notification[] = [
  // Mubarak (client_1)
  {
    id: 'notif_01',
    userId: 'user_c1',
    type: 'BOOKING_ACCEPTED',
    title: 'Booking accepted',
    body: 'Taiwo Ogundimu has accepted your painting job. Work starts Monday.',
    isRead: false,
    actionUrl: '/dashboard/my-hires',
    createdAt: '2025-01-08T16:10:00Z',
  },
  {
    id: 'notif_02',
    userId: 'user_c1',
    type: 'NEW_MESSAGE',
    title: 'New message from Taiwo',
    body: "I'll start with the master bedroom tomorrow morning at 8am.",
    isRead: false,
    actionUrl: '/dashboard/messages',
    createdAt: '2025-01-12T17:46:00Z',
  },
  {
    id: 'notif_03',
    userId: 'user_c1',
    type: 'PAYMENT_RELEASED',
    title: 'Escrow released',
    body: '₦162,000 has been released to Victor Adeyemi for the rewiring job.',
    isRead: true,
    actionUrl: '/dashboard/my-hires',
    createdAt: '2024-10-08T18:05:00Z',
  },
  {
    id: 'notif_04',
    userId: 'user_c1',
    type: 'BOOKING_ACCEPTED',
    title: 'Booking confirmed',
    body: 'Victor Adeyemi confirmed your rewiring booking for 1st October.',
    isRead: true,
    actionUrl: '/dashboard/my-hires',
    createdAt: '2024-09-28T11:00:00Z',
  },

  // Ibiso (client_2)
  {
    id: 'notif_05',
    userId: 'user_c2',
    type: 'PAYMENT_RECEIVED',
    title: 'Escrow deposit received',
    body: 'Your ₦320,000 escrow deposit for the kitchen cabinet job has been received.',
    isRead: false,
    actionUrl: '/dashboard/my-hires',
    createdAt: '2025-01-18T09:15:00Z',
  },
  {
    id: 'notif_06',
    userId: 'user_c2',
    type: 'NEW_MESSAGE',
    title: 'Message from Emmanuel',
    body: 'Please confirm the hinge type — soft-close or standard?',
    isRead: false,
    actionUrl: '/dashboard/messages',
    createdAt: '2025-01-19T11:22:00Z',
  },

  // Victor (provider_1)
  {
    id: 'notif_07',
    userId: 'user_p1',
    type: 'BOOKING_REQUEST',
    title: 'New booking request',
    body: 'Yemi Adesanya has requested an electrical fault inspection in Bodija.',
    isRead: false,
    actionUrl: '/dashboard/bookings',
    createdAt: '2025-01-13T11:10:00Z',
  },
  {
    id: 'notif_08',
    userId: 'user_p1',
    type: 'PAYMENT_RELEASED',
    title: 'Payment released',
    body: '₦162,000 has been credited to your wallet for the Lekki rewiring job.',
    isRead: false,
    actionUrl: '/dashboard/analytics',
    createdAt: '2024-10-08T18:10:00Z',
  },
  {
    id: 'notif_09',
    userId: 'user_p1',
    type: 'JOB_REVIEW',
    title: 'New 5-star review',
    body: 'Mubarak Eze left you a 5-star review: "Excellent work, very neat and professional."',
    isRead: true,
    actionUrl: '/dashboard/analytics',
    createdAt: '2024-10-09T10:00:00Z',
  },

  // Taiwo (provider_3)
  {
    id: 'notif_10',
    userId: 'user_p3',
    type: 'BOOKING_REQUEST',
    title: 'New job in Lagos',
    body: 'Mubarak Eze has booked you to paint a 3-bedroom flat in Victoria Island.',
    isRead: false,
    actionUrl: '/dashboard/bookings',
    createdAt: '2025-01-08T14:05:00Z',
  },
  {
    id: 'notif_11',
    userId: 'user_p3',
    type: 'BOOKING_DECLINED',
    title: 'Booking could not proceed',
    body: 'The epoxy flooring job in Kano was cancelled by the client.',
    isRead: true,
    actionUrl: '/dashboard/bookings',
    createdAt: '2025-01-20T16:00:00Z',
  },

  // Emmanuel (provider_2)
  {
    id: 'notif_12',
    userId: 'user_p2',
    type: 'PAYMENT_RECEIVED',
    title: 'Escrow received',
    body: '₦320,000 escrow has been deposited for the kitchen cabinet project.',
    isRead: false,
    actionUrl: '/dashboard/analytics',
    createdAt: '2025-01-18T09:20:00Z',
  },

  // Emeka (provider_5)
  {
    id: 'notif_13',
    userId: 'user_p5',
    type: 'BOOKING_REQUEST',
    title: 'New fence project',
    body: 'Chukwuma Obi has booked you for a perimeter fence construction in Enugu GRA.',
    isRead: false,
    actionUrl: '/dashboard/bookings',
    createdAt: '2025-01-20T14:10:00Z',
  },
];
